#pragma once
#include <BWAPI.h>
#include <vector>
#include <unordered_map>
#include "BWEB/Source/BWEB.h"
#include <map>

#define PYLON_POWER_WIDTH 16
#define PYLON_POWER_HEIGHT 10
#define MINIMUM_LARGE_POWERED_PLACEMENTS 4
#define MINIMUM_MEDIUM_POWERED_PLACEMENTS 2

//Need to keep track of different blocks sizes somehow
//Large Blocks have atleast 2 more large placements
//Medium Blocks have 1 large placement or 1/2 medium placements.
//Small Blocks are anything otherwise.

class BuildManager;

/// <summary>
/// When an attempt to find a location to place a building fails, the PlacementInfo struct is able to provide the details on what exactly is preventing us from building.
/// \n\nProtoBot not being able to build can happen because of many reasons:
/// \n - Tiles is not powered.
/// \n - No BWEB geenerated places for supply left to build.
/// \n - No avalible gysers are avalible for a refinery.
/// \n - No BWEB blocks for buildings are all used.
/// \n - No avalible expansion locations are avalible.
/// </summary>
struct PlacementInfo
{
	enum PlacementFlag { SUCCESS, NO_POWER, NO_BLOCKS, NO_GYSERS, NO_PLACEMENTS, NO_EXPANSIONS, DEFAULT };
	PlacementFlag flag = PlacementFlag::DEFAULT;

	BWAPI::Position position = BWAPI::Positions::Invalid;
	BWAPI::TilePosition topLeft = BWAPI::TilePositions::Invalid;
};

/// <summary>
/// The BWEB does not store the data about the specification of a block. The class BlockData allows the BuildingPlacer to preprocess Blocks generated by the BWEB to be able to distinguish the amount of possible placements we have.
/// </summary>
struct BlockData {

	enum BlockSize {LARGE, MEDIUM, SUPPLY, UNDEFINED};
	BlockSize Blocksize = BlockSize::UNDEFINED;

	//Only matters for Medium and Large Blocks
	enum PowerState {FULLY_POWERED, HALF_POWERED, NOT_POWERED};
	PowerState Power_State = PowerState::NOT_POWERED;

	int Large_Placements = 0;
	int Medium_Placements = 0; 
	int Power_Placements = 0; //Blocks used to power other medium and large building locations, 2x2 blocks will use this as a counter.

	int Used_Power_Placements = 0;

	//BWEM Area a block is located in.
	const BWEM::Area* Block_AreaLocation; 

	std::set<BWAPI::TilePosition> PowerTiles;
};

/// <summary>
/// The BuildingPlacer is the way ProtoBot is able to utilize the BWEB blocks generated to place down buildings. This allows for a single class to be able to find places to build and returns information about the placement info if anything goes wrong.
/// \n\n
/// When the BuildingPlacer is first created the Blocks that generated are stored into lists that ProtoBot is able to use based on the building type of a ResourceRequest. This allows the BuildingPlacer to find a suitable generated locations without having to loop through ever single block on the map.
/// \n More blocks are added based on the areas the ProtoBot controls. To prevent the risk of ProtoBot building in enemy territory, ProtoBot will only build in the areas that ProtoBot currently 'controls'. When a nexus is created this expands ProtoBot's influence and makes more blocks avalible if any are generated in that location.
/// 
/// </summary>
class BuildingPlacer
{
private:
	//Might not need these and just want to store the info in BlockData
	//std::vector<std::vector<int>> poweredTiles;

	std::map<BWAPI::TilePosition, BlockData> Block_Information;

	//Might need this to make getting blocks in Areas we own easier.
	std::unordered_set<const BWEM::Area *> AreasOccupied;

	//List of all the blocks from the areas we own.
	std::vector<BWEB::Block> ProtoBot_Blocks;

	//All the Areas the BWEM has and the blocks that are assigned to them. For the purpose of expanding our base we will only place in areas we own.
	//This should not apply to Walls, Proxy, and Cheeses.
	std::unordered_map<const BWEM::Area*, std::vector<BWEB::Block>> Area_Blocks;

	int mapWidth = 0;
	int mapHeight = 0;

	//Adding this as fail safe to give us access to more Blocks
	int nexusCount = 0;

	bool debug = false;

public:
	int Powered_LargePlacements = 0;
	int Powered_MediumPlacements = 0;
	int Used_LargeBuildingPlacements;
	int Used_MediumBuildingPlacements;
	BuildManager* buildReference;

	BuildingPlacer(BuildManager* buildReference);
	PlacementInfo getPositionToBuild(BWAPI::UnitType, const BWEM::Base*);

	/// <summary>
	/// Checks if a location to place a building already has another unit ontop of it (will only consider buildings not combat units). 
	/// </summary>
	/// <param name="Top Left Tile Position to place building"></param>
	/// <param name="Width"></param>
	/// <param name="Height"></param>
	/// <param name="isAssimilator"></param>
	/// <returns>TilePosition to build</returns>
	bool alreadyUsingTiles(BWAPI::TilePosition, int, int, bool assimilator);
	bool checkPower(BWAPI::TilePosition, BWAPI::UnitType);

	/// <summary>
	/// Finda an available Block that has no power in the power tile location.
	/// </summary>
	/// <returns>TilePosition to build</returns>
	BWAPI::TilePosition checkBuildingBlocks();

	/// <summary>
	/// Checks Blocks of size 2x2 (tiles) that can be used in order to place down pylons for supply.
	/// </summary>
	/// <returns>TilePosition to build</returns>
	BWAPI::TilePosition checkPowerReserveBlocks();

	/// <summary>
	/// Checks BWEM expansion locations for possible place to construct resource depot.
	/// </summary>
	/// <returns>TilePosition to build</returns>
	BWAPI::TilePosition findAvailableExpansion();

	/// <summary>
	/// Checks a base to place down an assimlator ontop of a vespene gyser.
	/// </summary>
	/// <param name="Base (expansion location)"></param>
	/// <returns>TilePosition to build</returns>
	BWAPI::TilePosition findAvailableGyser(const BWEM::Base*);

	/// <summary>
	/// Standard call for buildings to find a location to be placed other than refineries, resource depots, and supply units. 
	/// </summary>
	/// <param name="UnitType (building type to be constructed)"></param>
	/// <returns>TilePosition to build</returns>
	BWAPI::TilePosition findAvaliblePlacement(BWAPI::UnitType);
	int numberOfFullPoweredLargePlacements();

	void drawPoweredTiles();

	/// <summary>
	/// Update Block information to reflect generated BWEB Blocks and reset values to reflect a beggining game state.
	/// </summary>
	void onStart();

	/// <summary>
	/// Updates BWEM to reflect the current state of StarCraft game.
	/// </summary>
	/// <param name="Unit"></param>
	void onUnitCreate(BWAPI::Unit);

	/// <summary>
	/// Updates BWEM to reflect the current state of StarCraft game.
	/// </summary>
	/// <param name="Unit"></param>
	void onUnitComplete(BWAPI::Unit);

	/// <summary>
	/// Updates BWEM to reflect the current state of StarCraft game.
	/// </summary>
	/// <param name="Unit"></param>
	void onUnitDestroy(BWAPI::Unit);

	/// <summary>
	/// Updates BWEM to reflect the current state of StarCraft game.
	/// </summary>
	/// <param name="Unit"></param>
	void onUnitMorph(BWAPI::Unit);

	/// <summary>
	/// Updates BWEM to reflect the current state of StarCraft game.
	/// </summary>
	/// <param name="Unit"></param>
	void onUnitDiscover(BWAPI::Unit);
};

